  -- SQL LITE MODE

CREATE TABLE "BEER_USERS" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"IP"	TEXT NOT NULL,
	"PORT"	INTEGER NOT NULL,
	"USERNAME"	TEXT NOT NULL UNIQUE,
	"NAME"	TEXT NOT NULL,
	"AGE"	INTEGER NOT NULL,
	"SEX"	TEXT NOT NULL,
	"LOCATION"	TEXT NOT NULL
)