-- Oracle Mode

CREATE TABLE BEER_USERS (ID NUMBER(10) NOT NULL, IP VARCHAR2(16) NOT NULL, PORT NUMBER(4) NOT NULL, USERNAME VARCHAR2(100) NOT NULL, NAME VARCHAR2(128) NOT NULL, AGE NUMBER(4) NOT NULL, SEX VARCHAR(1) NOT NULL, LOCATION VARCHAR2(2) NOT NULL );

ALTER TABLE BEER_USERS
    ADD CONSTRAINT BEER_C_PK_USERS PRIMARY KEY ( id );
    
CREATE UNIQUE INDEX BEER_I_US_USERNAME ON
    BEER_USERS (
        USERNAME
    ASC );
    
CREATE SEQUENCE BEER_SEQ_USERS START WITH 1 INCREMENT BY 1 MAXVALUE 2147483647 MINVALUE 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER BEER_T_SEQ_USERS
BEFORE INSERT ON BEER_USERS
FOR EACH ROW
BEGIN
	IF :new.ID IS NULL THEN
		SELECT BEER_SEQ_USERS.nextval INTO :new.ID FROM DUAL;
	END IF;
END;
/

ALTER TABLE BEER_USERS
ADD CONSTRAINT BEER_C_CHECK_USER_ID
  CHECK (AGE >= 18);


ALTER TABLE BEER_USERS
ADD CONSTRAINT BEER_C_CHECK_USER_SEX
  CHECK (SEX IN ('M', 'H', 'O'));
